control_frequency: 50.0

robot_config:
  robot_type: "ur"
  has_effort_feedback: true

gripper_config: null
camera_configs: []
sensor_configs:
  - sensor_type: "force_torque"
    name: "ft_sensor"
    data_topic: "/force_torque_sensor_broadcaster/wrench"

gripper_mode: "none"

cartesian_control_param_config: "control/ur_cartesian_impedance.yaml"
joint_control_param_config: "control/ur_joint_control.yaml"
