"""Relative-pose dataset wrapper and training launcher for LeRobot 0.4.4.

Implements UMI's relative pose representation at dataloader level: every pose
(observation history and action horizon) is re-expressed relative to the
current observed TCP pose — T_rel = T_current^{-1} @ T_target — after
LeRobot's temporal sampling (delta_timestamps) has stacked the frames.

Pose layout (matching UMI / pytorch3d rotation-6d convention):
    observation.state.cartesian : [x, y, z, rot6d(6)]            -> 9D
    action                      : [x, y, z, rot6d(6), gripper]   -> 10D
The rot6d encoding is the first two ROWS of the rotation matrix, flattened;
decoding uses Gram-Schmidt orthogonalization (same as UMI's rot6d_to_mat).

The dataset on disk stays in absolute poses. With diffusion policy's default
n_obs_steps=2, the wrapper produces:

    observation.state.cartesian     (2, 9):  [t-1 rel. to t, identity]
                                    identity rot6d = [1,0,0, 0,1,0], pos = 0
    observation.state.rot_wrt_start (2, 6):  rot6d of each obs frame relative
                                    to the (noised) episode-start pose — UMI's
                                    robot0_eef_rot_axis_angle_wrt_start analog
    action                          (16, 10): each step rel. to t, gripper raw

Normalization stats are recomputed on the relative values (LeRobot normalizes
with dataset-wide stats which were computed on absolute poses and would
otherwise be wrong).

Usage on the training PC (lerobot==0.4.4 installed):

    python lerobot_relative_pose.py \\
        --dataset.repo_id=my_org/umi_demo \\
        --policy.type=diffusion \\
        --output_dir=outputs/train/umi_relative \\
        ... (any other lerobot-train args)

Note: observation.state.rot_wrt_start is generated by this wrapper and is NOT
in dataset.meta.features — to feed it to the policy, declare it as an input
feature in the policy config.

At inference, invert with: T_cmd = T_current_robot_tcp @ T_rel  (compose the
policy's relative output with the robot's current TCP pose in its own base
frame — no OptiTrack-to-robot calibration needed).
"""

from __future__ import annotations

import logging

import numpy as np
import torch

logger = logging.getLogger(__name__)

# Keys holding absolute poses as [x, y, z, rot6d(6)(, gripper...)]
POSE_OBS_KEYS = ["observation.state.cartesian"]
POSE_ACTION_KEY = "action"
# Which key provides the "current" base pose (last frame of its window)
BASE_KEY = "observation.state.cartesian"
# Wrapper-generated observation: rot6d of each obs frame wrt episode start
WRT_START_KEY = "observation.state.rot_wrt_start"
# Noise scale added to the episode-start pose (UMI's HACK, umi_dataset.py:314)
START_POSE_NOISE_SCALE = 0.05


# ── rot6d <-> matrix (UMI/pytorch3d convention: first two rows) ───────────────
# LOCAL COPY by design: this script must stay crisp-import-free (GPU PC).
# Canonical in-package version: crisp_gym/util/rot6d.py — keep them identical
# (tests/test_pose_math.py pins the convention numerically).

def rot6d_to_mat(d6: np.ndarray) -> np.ndarray:
    """[..., 6] rot6d -> [..., 3, 3] via Gram-Schmidt (UMI's rot6d_to_mat)."""
    a1, a2 = d6[..., :3], d6[..., 3:]
    b1 = a1 / np.linalg.norm(a1, axis=-1, keepdims=True)
    b2 = a2 - np.sum(b1 * a2, axis=-1, keepdims=True) * b1
    b2 = b2 / np.linalg.norm(b2, axis=-1, keepdims=True)
    b3 = np.cross(b1, b2, axis=-1)
    return np.stack((b1, b2, b3), axis=-2)


def mat_to_rot6d(mat: np.ndarray) -> np.ndarray:
    """[..., 3, 3] -> [..., 6]: first two rows flattened."""
    batch = mat.shape[:-2]
    return mat[..., :2, :].reshape(*batch, 6).copy()


def pose9d_to_mat(pose: np.ndarray) -> np.ndarray:
    """[..., 9] (pos + rot6d) -> [..., 4, 4] homogeneous matrices."""
    pose = np.asarray(pose, dtype=np.float64)
    batch = pose.shape[:-1]
    T = np.tile(np.eye(4), (*batch, 1, 1))
    T[..., :3, :3] = rot6d_to_mat(pose[..., 3:9])
    T[..., :3, 3] = pose[..., :3]
    return T


def mat_to_pose9d(T: np.ndarray) -> np.ndarray:
    """[..., 4, 4] -> [..., 9] (pos + rot6d)."""
    pos = T[..., :3, 3]
    rot6d = mat_to_rot6d(T[..., :3, :3])
    return np.concatenate([pos, rot6d], axis=-1)


def make_relative(base_pose9d: np.ndarray, poses9d: np.ndarray) -> np.ndarray:
    """Express poses9d [..., 9] relative to base_pose9d [9]: T_base^-1 @ T."""
    T_base_inv = np.linalg.inv(pose9d_to_mat(base_pose9d))
    T = pose9d_to_mat(poses9d)
    return mat_to_pose9d(T_base_inv @ T)


# ── Dataset wrapper ───────────────────────────────────────────────────────────

class RelativePoseDataset(torch.utils.data.Dataset):
    """Wraps a LeRobotDataset; converts absolute poses to relative in __getitem__.

    The base frame is the LAST timestep of BASE_KEY's window (the current
    observation, delta index 0), matching UMI's pose_mat[-1]. Also emits
    WRT_START_KEY: rot6d of each obs frame relative to the episode-start pose
    (with noise, rotation-only — UMI's *_rot_axis_angle_wrt_start).
    """

    def __init__(self, dataset, start_pose_noise_scale: float = START_POSE_NOISE_SCALE):
        self._dataset = dataset
        self._start_pose_noise_scale = start_pose_noise_scale
        self._episode_start_pose: dict[int, np.ndarray] = {}

    def __len__(self) -> int:
        return len(self._dataset)

    def __getattr__(self, name):
        # Delegate everything else (.meta, .num_frames, .episodes, ...)
        return getattr(self._dataset, name)

    @staticmethod
    def _to_np(v) -> np.ndarray:
        return v.numpy() if isinstance(v, torch.Tensor) else np.asarray(v)

    def _get_start_pose(self, idx: int, item: dict) -> np.ndarray | None:
        """Absolute episode-start pose [9] for the episode containing idx (cached)."""
        if "episode_index" not in item or "frame_index" not in item:
            return None
        ep = int(self._to_np(item["episode_index"]))
        if ep not in self._episode_start_pose:
            frame = int(self._to_np(item["frame_index"]))
            # Read frame-0's pose from the low-dim hf_dataset directly. Going
            # through self._dataset[...] would DECODE VIDEO for that frame just
            # to read one pose — expensive and pointless. hf_dataset holds the
            # low-dim columns only (no video), so this is a cheap lookup.
            start_pose = None
            hf = getattr(self._dataset, "hf_dataset", None)
            if hf is not None:
                try:
                    row = hf[int(idx - frame)]
                    start_pose = self._to_np(row[BASE_KEY])
                except Exception:
                    start_pose = None
            if start_pose is None:
                # Fallback: the video-decoding path (older/edge datasets).
                start_window = self._to_np(self._dataset[idx - frame][BASE_KEY])
                start_pose = start_window[-1] if start_window.ndim == 2 else start_window
            else:
                start_pose = start_pose[-1] if start_pose.ndim == 2 else start_pose
            self._episode_start_pose[ep] = start_pose[:9].astype(np.float64)
        return self._episode_start_pose[ep]

    def convert_item(self, item: dict, start_pose: np.ndarray | None = None) -> dict:
        base = self._to_np(item[BASE_KEY])
        base_pose = (base[-1] if base.ndim == 2 else base)[:9].astype(np.float64)

        # Rotation wrt (noised) episode start — computed BEFORE overwriting obs
        if start_pose is not None:
            noised = start_pose.copy()
            if self._start_pose_noise_scale > 0:
                # Perturb position and rotation (via rot6d columns) like UMI's
                # additive noise on the raw start-pose vector.
                noised = noised + np.random.normal(
                    scale=self._start_pose_noise_scale, size=noised.shape
                )
            obs_abs = self._to_np(item[BASE_KEY]).astype(np.float64)
            if obs_abs.ndim == 1:
                obs_abs = obs_abs[None]
            rel_to_start = make_relative(noised, obs_abs[..., :9])
            item[WRT_START_KEY] = torch.from_numpy(
                rel_to_start[..., 3:9].astype(np.float32)
            )

        for key in POSE_OBS_KEYS:
            if key not in item:
                continue
            v = self._to_np(item[key]).astype(np.float64)
            rel = make_relative(base_pose, v[..., :9])
            item[key] = torch.from_numpy(rel.astype(np.float32))

        if POSE_ACTION_KEY in item:
            a = self._to_np(item[POSE_ACTION_KEY]).astype(np.float64)
            rel = make_relative(base_pose, a[..., :9])
            out = np.concatenate([rel, a[..., 9:]], axis=-1)
            item[POSE_ACTION_KEY] = torch.from_numpy(out.astype(np.float32))

        return item

    def __getitem__(self, idx: int) -> dict:
        item = self._dataset[idx]
        start_pose = self._get_start_pose(idx, item)
        return self.convert_item(item, start_pose=start_pose)


# ── Stats recomputation ───────────────────────────────────────────────────────

def recompute_relative_stats(wrapped: RelativePoseDataset, num_samples: int = 2000) -> None:
    """Patch dataset.meta.stats for pose keys with stats of the RELATIVE values.

    LeRobot's NormalizerProcessor uses dataset-wide stats computed on the raw
    (absolute) Parquet values. After the relative conversion the distributions
    are completely different, so we sample the wrapped dataset and overwrite
    the stats for the converted keys (and add stats for WRT_START_KEY).
    """
    keys = [k for k in POSE_OBS_KEYS] + [POSE_ACTION_KEY, WRT_START_KEY]
    n = len(wrapped)
    indices = np.linspace(0, n - 1, min(num_samples, n)).astype(int)

    # CRITICAL: do NOT decode video in this pass. It runs in the MAIN process,
    # and any torchcodec decoder opened here is forked into the DataLoader
    # workers in a broken state -> every worker dies at step 0 with
    # "Could not push packet to decoder: Invalid data found". (Plain
    # lerobot-train has no main-process stats pass, which is why it never hits
    # this.) The stats keys are all low-dim poses, so we no-op the dataset's
    # video query for the duration of sampling; lerobot's temporal windowing of
    # the low-dim columns is unaffected, so the action-horizon stats stay exact.
    ds = wrapped._dataset
    _orig_query_videos = getattr(ds, "_query_videos", None)
    if _orig_query_videos is not None:
        ds._query_videos = lambda *a, **k: {}
    try:
        collected: dict[str, list[np.ndarray]] = {k: [] for k in keys}
        for i in indices:
            item = wrapped[int(i)]
            for k in keys:
                if k in item:
                    v = item[k]
                    v = v.numpy() if isinstance(v, torch.Tensor) else np.asarray(v)
                    collected[k].append(v.reshape(-1, v.shape[-1]))
    finally:
        if _orig_query_videos is not None:
            ds._query_videos = _orig_query_videos

    for k, chunks in collected.items():
        if not chunks:
            continue
        data = np.concatenate(chunks, axis=0)
        wrapped.meta.stats[k] = {
            "mean": torch.from_numpy(data.mean(axis=0).astype(np.float32)),
            "std": torch.from_numpy((data.std(axis=0) + 1e-8).astype(np.float32)),
            "min": torch.from_numpy(data.min(axis=0).astype(np.float32)),
            "max": torch.from_numpy(data.max(axis=0).astype(np.float32)),
        }
        logger.info(f"Recomputed relative-pose stats for '{k}' over {len(data)} frames.")


# ── Provenance stamping ───────────────────────────────────────────────────────

def stamp_pose_repr(cfg, dataset) -> None:
    """Write pose_repr.json next to the checkpoints (HANDOFF §4.2).

    Records what the model ACTUALLY sees, so the serving side (remote policy
    server / local RelativeLerobotPolicy) can verify its contract instead of
    guessing. Never fails training.
    """
    import json
    from pathlib import Path

    try:
        pol = getattr(cfg, "policy", None)
        meta = getattr(dataset, "meta", None)
        info = {
            "pose_layout": "pos3_rot6d_rows",
            "rot6d_convention": "first_two_rows_row_major_gram_schmidt_decode",
            "action": {
                "pose_repr": "relative",
                "base": "last_obs_frame_tcp",
                "compose_base": "obs_time",
                "layout": "[x, y, z, rot6d(6), gripper]",
            },
            "observation": {
                # lerobot-0.4.4 policies consume the CONCATENATED
                # observation.state, which this wrapper does NOT convert:
                # the state input is ABSOLUTE [cartesian9, gripper_ref1].
                "observation.state": "absolute",
                # The sub-key IS converted (relative to the last obs frame)
                # but is not read by 0.4.4 policies — normalizer passthrough.
                "observation.state.cartesian": "relative_to_last_obs_frame",
                "wrt_start_key": WRT_START_KEY,
                "start_pose_noise_scale": START_POSE_NOISE_SCALE,
            },
            "gripper": {
                "semantics": "clip(width_m / reference_width, 0, 1)",
                "note": "reference_width/device_max_width are stamped in the "
                        "dataset's meta/record_config.json",
            },
            "normalization": "relative stats recomputed pre-training "
                             "(recompute_relative_stats), saved with checkpoint",
            "fps": getattr(meta, "fps", None),
            "n_obs_steps": getattr(pol, "n_obs_steps", None),
            "horizon": getattr(pol, "horizon", None),
            "n_action_steps": getattr(pol, "n_action_steps", None),
            "lerobot_version_target": "0.4.4",
        }
        out_dir = Path(cfg.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "pose_repr.json").write_text(json.dumps(info, indent=2))
        logger.info(f"Stamped {out_dir / 'pose_repr.json'}")
    except Exception as e:  # provenance must never kill a training run
        logger.warning(f"Could not stamp pose_repr.json: {e}")


# ── Training launcher ─────────────────────────────────────────────────────────

def main():
    """Run lerobot-train with the relative-pose dataset wrapper injected."""
    import lerobot.scripts.lerobot_train as lerobot_train

    original_make_dataset = lerobot_train.make_dataset

    def make_dataset_with_relative(cfg):
        dataset = original_make_dataset(cfg)
        wrapped = RelativePoseDataset(dataset)
        logger.info("Wrapped dataset with RelativePoseDataset (UMI-style relative poses).")
        recompute_relative_stats(wrapped)
        stamp_pose_repr(cfg, wrapped)
        return wrapped

    lerobot_train.make_dataset = make_dataset_with_relative

    logging.basicConfig(level=logging.INFO)
    lerobot_train.main()


if __name__ == "__main__":
    main()
