"""Relative-pose dataset wrapper and training launcher for LeRobot.

Supports lerobot 0.4.x and >=0.5 (verified against 0.4.4 and 0.6.1) — see
main() for the version-dependent dataset-factory patch.

Implements UMI's relative pose representation at dataloader level: every pose
(observation history and action horizon) is re-expressed relative to the
current observed TCP pose — T_rel = T_current^{-1} @ T_target — after
LeRobot's temporal sampling (delta_timestamps) has stacked the frames.

Pose layout (matching UMI / pytorch3d rotation-6d convention):
    observation.state.cartesian : [x, y, z, rot6d(6)]            -> 9D
    action                      : [x, y, z, rot6d(6), gripper]   -> 10D
The rot6d encoding is the first two ROWS of the rotation matrix, flattened;
decoding uses Gram-Schmidt orthogonalization (same as UMI's rot6d_to_mat).

The dataset on disk stays in absolute poses. With diffusion policy's default
n_obs_steps=2, the wrapper produces:

    observation.state               (2, 16): [rel_pose9, gripper1, wrt_start6]
                                    — the CONCATENATED key lerobot
                                    policies actually consume (OBS_STATE):
                                    pose dims converted like the sub-key below,
                                    then the wrt-start rot6d appended (UMI's
                                    16-D low-dim input; position-wrt-start is
                                    deliberately excluded, as in UMI)
    observation.state.cartesian     (2, 9):  [t-1 rel. to t, identity]
                                    identity rot6d = [1,0,0, 0,1,0], pos = 0
    observation.state.rot_wrt_start (2, 6):  rot6d of each obs frame relative
                                    to the (noised) episode-start pose — UMI's
                                    robot0_eef_rot_axis_angle_wrt_start analog
    action                          (16, 10): each step rel. to t, gripper raw

Checkpoints trained BEFORE observation.state was converted saw ABSOLUTE state
input; the stamped pose_repr.json disambiguates (missing file => absolute).

Normalization stats are recomputed on the relative values (LeRobot normalizes
with dataset-wide stats which were computed on absolute poses and would
otherwise be wrong).

Usage on the training PC (lerobot 0.4.x or >=0.5 installed):

    python lerobot_relative_pose.py \\
        --dataset.repo_id=my_org/umi_demo \\
        --dataset.root=/path/to/dataset \\
        --policy.type=diffusion --policy.push_to_hub=false \\
        --output_dir=outputs/train/umi_relative \\
        [--no-wrt-start] ... (any other lerobot-train args)

Flag --wrt-start / --no-wrt-start (ours, stripped before lerobot parses):
  --wrt-start (default): 16-D UMI-parity observation.state (rot_wrt_start
      appended) — deploy with state_input: relative_wrt_start.
  --no-wrt-start:        plain 10-D relative state — deploy with state_input:
      relative.

Note: observation.state.rot_wrt_start is generated by this wrapper and is NOT
in dataset.meta.features — to feed it to the policy, declare it as an input
feature in the policy config. (Only relevant with --wrt-start.)

At inference, invert with: T_cmd = T_current_robot_tcp @ T_rel  (compose the
policy's relative output with the robot's current TCP pose in its own base
frame — no OptiTrack-to-robot calibration needed).
"""

from __future__ import annotations

import logging

import numpy as np
import torch

logger = logging.getLogger(__name__)

# Keys holding absolute poses as [x, y, z, rot6d(6)(, gripper...)]
POSE_OBS_KEYS = ["observation.state.cartesian"]
POSE_ACTION_KEY = "action"
# The CONCATENATED state [cartesian9, gripper1, ...]: this is the key
# lerobot-0.4.4 policies actually consume (OBS_STATE queue) — converting only
# the .cartesian sub-key leaves the MODEL INPUT absolute. Its first 9 dims are
# converted like the sub-key; trailing dims (gripper, promoted extras) pass
# through untouched.
STATE_KEY = "observation.state"
# Which key provides the "current" base pose (last frame of its window)
BASE_KEY = "observation.state.cartesian"
# Wrapper-generated observation: rot6d of each obs frame wrt episode start
WRT_START_KEY = "observation.state.rot_wrt_start"
# Noise scale added to the episode-start pose (UMI's HACK, umi_dataset.py:314)
START_POSE_NOISE_SCALE = 0.05


# ── rot6d <-> matrix (UMI/pytorch3d convention: first two rows) ───────────────
# LOCAL COPY by design: this script must stay crisp-import-free (GPU PC).
# Canonical in-package version: crisp_gym/util/rot6d.py — keep them identical
# (tests/test_pose_math.py pins the convention numerically).

def rot6d_to_mat(d6: np.ndarray) -> np.ndarray:
    """[..., 6] rot6d -> [..., 3, 3] via Gram-Schmidt (UMI's rot6d_to_mat)."""
    a1, a2 = d6[..., :3], d6[..., 3:]
    b1 = a1 / np.linalg.norm(a1, axis=-1, keepdims=True)
    b2 = a2 - np.sum(b1 * a2, axis=-1, keepdims=True) * b1
    b2 = b2 / np.linalg.norm(b2, axis=-1, keepdims=True)
    b3 = np.cross(b1, b2, axis=-1)
    return np.stack((b1, b2, b3), axis=-2)


def mat_to_rot6d(mat: np.ndarray) -> np.ndarray:
    """[..., 3, 3] -> [..., 6]: first two rows flattened."""
    batch = mat.shape[:-2]
    return mat[..., :2, :].reshape(*batch, 6).copy()


def pose9d_to_mat(pose: np.ndarray) -> np.ndarray:
    """[..., 9] (pos + rot6d) -> [..., 4, 4] homogeneous matrices."""
    pose = np.asarray(pose, dtype=np.float64)
    batch = pose.shape[:-1]
    T = np.tile(np.eye(4), (*batch, 1, 1))
    T[..., :3, :3] = rot6d_to_mat(pose[..., 3:9])
    T[..., :3, 3] = pose[..., :3]
    return T


def mat_to_pose9d(T: np.ndarray) -> np.ndarray:
    """[..., 4, 4] -> [..., 9] (pos + rot6d)."""
    pos = T[..., :3, 3]
    rot6d = mat_to_rot6d(T[..., :3, :3])
    return np.concatenate([pos, rot6d], axis=-1)


def make_relative(base_pose9d: np.ndarray, poses9d: np.ndarray) -> np.ndarray:
    """Express poses9d [..., 9] relative to base_pose9d [9]: T_base^-1 @ T."""
    T_base_inv = np.linalg.inv(pose9d_to_mat(base_pose9d))
    T = pose9d_to_mat(poses9d)
    return mat_to_pose9d(T_base_inv @ T)


# ── Dataset wrapper ───────────────────────────────────────────────────────────

class RelativePoseDataset(torch.utils.data.Dataset):
    """Wraps a LeRobotDataset; converts absolute poses to relative in __getitem__.

    The base frame is the LAST timestep of BASE_KEY's window (the current
    observation, delta index 0), matching UMI's pose_mat[-1]. Also emits
    WRT_START_KEY: rot6d of each obs frame relative to the episode-start pose
    (with noise, rotation-only — UMI's *_rot_axis_angle_wrt_start).
    """

    def __init__(
        self,
        dataset,
        start_pose_noise_scale: float = START_POSE_NOISE_SCALE,
        append_wrt_start_to_state: bool = True,
    ):
        self._dataset = dataset
        self._start_pose_noise_scale = start_pose_noise_scale
        # UMI parity: append the wrt-start rot6d to the CONCATENATED state so
        # the policy actually consumes it (UMI's 16-D low-dim input:
        # eef_pos(3) + eef_rot6d(6) + gripper(1) + rot_wrt_start(6); position
        # wrt start stays deliberately excluded, as in UMI). Requires items to
        # carry episode/frame indices (any LeRobotDataset does).
        self._append_wrt = append_wrt_start_to_state
        self._episode_start_pose: dict[int, np.ndarray] = {}

        # The policy's input layer + normalizer are sized from meta.features
        # BEFORE conversion, so widen observation.state there to match.
        if append_wrt_start_to_state and dataset is not None:
            features = getattr(getattr(dataset, "meta", None), "features", None)
            if features and STATE_KEY in features:
                feat = dict(features[STATE_KEY])
                old_dim = int(np.prod(feat["shape"]))
                feat["shape"] = (old_dim + 6,)
                feat["names"] = list(feat.get("names") or []) + [
                    f"rot_wrt_start_{i}" for i in range(6)
                ]
                features[STATE_KEY] = feat
                logger.info(
                    f"{STATE_KEY}: widened {old_dim} -> {old_dim + 6} dims "
                    "(appended rot_wrt_start, UMI parity)."
                )

    def __len__(self) -> int:
        return len(self._dataset)

    def __getattr__(self, name):
        # Delegate everything else (.meta, .num_frames, .episodes, ...) to the
        # wrapped dataset. __getattr__ fires ONLY when normal lookup fails; under
        # a 'spawn' DataLoader the dataset is pickled and, during unpickling,
        # __dict__ is not yet populated, so `_dataset` is absent — a plain
        # `self._dataset` would re-enter __getattr__ and recurse forever
        # (RecursionError in the workers). Read it straight from __dict__ and
        # raise AttributeError when it isn't there yet, so pickle falls back to
        # its default protocol.
        try:
            dataset = self.__dict__["_dataset"]
        except KeyError:
            raise AttributeError(name)
        return getattr(dataset, name)

    @staticmethod
    def _to_np(v) -> np.ndarray:
        return v.numpy() if isinstance(v, torch.Tensor) else np.asarray(v)

    def _get_start_pose(self, idx: int, item: dict) -> np.ndarray | None:
        """Absolute episode-start pose [9] for the episode containing idx (cached)."""
        if "episode_index" not in item or "frame_index" not in item:
            return None
        ep = int(self._to_np(item["episode_index"]))
        if ep not in self._episode_start_pose:
            frame = int(self._to_np(item["frame_index"]))
            # Read frame-0's pose from the low-dim hf_dataset directly. Going
            # through self._dataset[...] would DECODE VIDEO for that frame just
            # to read one pose — expensive and pointless. hf_dataset holds the
            # low-dim columns only (no video), so this is a cheap lookup.
            start_pose = None
            hf = getattr(self._dataset, "hf_dataset", None)
            if hf is not None:
                try:
                    row = hf[int(idx - frame)]
                    start_pose = self._to_np(row[BASE_KEY])
                except Exception:
                    start_pose = None
            if start_pose is None:
                # Fallback: the video-decoding path (older/edge datasets).
                start_window = self._to_np(self._dataset[idx - frame][BASE_KEY])
                start_pose = start_window[-1] if start_window.ndim == 2 else start_window
            else:
                start_pose = start_pose[-1] if start_pose.ndim == 2 else start_pose
            self._episode_start_pose[ep] = start_pose[:9].astype(np.float64)
        return self._episode_start_pose[ep]

    def convert_item(self, item: dict, start_pose: np.ndarray | None = None) -> dict:
        base = self._to_np(item[BASE_KEY] if BASE_KEY in item else item[STATE_KEY])
        base_pose = (base[-1] if base.ndim == 2 else base)[:9].astype(np.float64)

        # Rotation wrt (noised) episode start — computed from the ABSOLUTE obs,
        # BEFORE any relative conversion overwrites them.
        rel_to_start = None
        if start_pose is not None:
            noised = start_pose.copy()
            if self._start_pose_noise_scale > 0:
                # Perturb position and rotation (via rot6d columns) like UMI's
                # additive noise on the raw start-pose vector.
                noised = noised + np.random.normal(
                    scale=self._start_pose_noise_scale, size=noised.shape
                )
            obs_key = BASE_KEY if BASE_KEY in item else STATE_KEY
            obs_abs = self._to_np(item[obs_key]).astype(np.float64)
            if obs_abs.ndim == 1:
                obs_abs = obs_abs[None]
            rel_to_start = make_relative(noised, obs_abs[..., :9])
            item[WRT_START_KEY] = torch.from_numpy(
                rel_to_start[..., 3:9].astype(np.float32)
            )

        for key in POSE_OBS_KEYS:
            if key not in item:
                continue
            v = self._to_np(item[key]).astype(np.float64)
            rel = make_relative(base_pose, v[..., :9])
            item[key] = torch.from_numpy(rel.astype(np.float32))

        # The concatenated state — the tensor 0.4.4 policies actually read.
        # Convert its pose dims so the MODEL INPUT is relative (current frame
        # -> identity); gripper / promoted extras (dims 9+) pass through; then
        # (UMI parity) append the wrt-start rot6d so the policy consumes it:
        # [rel_pose9, gripper1(, extras...), rot_wrt_start6].
        if STATE_KEY in item:
            v = self._to_np(item[STATE_KEY]).astype(np.float64)
            rel = make_relative(base_pose, v[..., :9])
            parts = [rel, v[..., 9:]]
            if self._append_wrt and rel_to_start is not None:
                wrt = rel_to_start[..., 3:9]
                if v.ndim == 1:  # single frame: rel_to_start is (1, 9)
                    wrt = wrt[0]
                parts.append(wrt)
            elif self._append_wrt:
                raise ValueError(
                    "append_wrt_start_to_state=True but no episode start pose "
                    "is available (items lack episode_index/frame_index, or "
                    "convert_item was called without start_pose). The state "
                    "dim would silently disagree with meta.features."
                )
            out = np.concatenate(parts, axis=-1)
            item[STATE_KEY] = torch.from_numpy(out.astype(np.float32))

        if POSE_ACTION_KEY in item:
            a = self._to_np(item[POSE_ACTION_KEY]).astype(np.float64)
            rel = make_relative(base_pose, a[..., :9])
            out = np.concatenate([rel, a[..., 9:]], axis=-1)
            item[POSE_ACTION_KEY] = torch.from_numpy(out.astype(np.float32))

        return item

    def __getitem__(self, idx: int) -> dict:
        item = self._dataset[idx]
        start_pose = self._get_start_pose(idx, item)
        return self.convert_item(item, start_pose=start_pose)


# ── Stats recomputation ───────────────────────────────────────────────────────

# Candidate names for LeRobotDataset's internal video-query method, newest to
# oldest. The stats pass disables it to avoid opening torchcodec decoders in the
# MAIN process — see HANDOFF §1.6. Kept as a list so a lerobot rename does not
# silently skip the guard where it IS needed (a FORKING DataLoader). lerobot
# 0.4.x used `_query_videos`; >=0.5 may have renamed it.
_VIDEO_QUERY_ATTRS = ("_query_videos", "_query_video", "query_videos")


def _forking_dataloader() -> bool:
    """Best-effort: will DataLoader workers FORK (inherit the parent's decoders)?

    The torchcodec crash (HANDOFF §1.6) is fork-ONLY: spawn/forkserver workers
    start fresh and never inherit the main process's broken decoders. lerobot
    >=0.5 defaults its DataLoader to 'spawn', so the no-op is usually moot there;
    it stays essential on 0.4.x / fork. get_start_method() is the process
    default, which is what lerobot uses when it does not pass an explicit context.
    """
    try:
        import multiprocessing as mp

        return mp.get_start_method(allow_none=True) == "fork"
    except Exception:
        return True  # unknown -> assume fork and warn, the safe side


def _disable_video_query(ds):
    """Temporarily no-op the dataset's video query. Returns (attr_name, original).

    Patches the first known method that exists. If NONE is found, the guard
    cannot be applied: warn ONLY when the DataLoader would fork (where the
    torchcodec crash is real). Under spawn (lerobot >=0.5 default) it is a
    non-issue, so stay quiet instead of crying wolf.
    """
    for name in _VIDEO_QUERY_ATTRS:
        if hasattr(ds, name):
            orig = getattr(ds, name)
            setattr(ds, name, lambda *a, **k: {})
            return name, orig
    if _forking_dataloader():
        logger.warning(
            "Could not find a video-query method on the dataset (tried %s) to "
            "disable video decode during the stats pass, and the DataLoader may "
            "FORK. If workers crash at step 0 with 'Could not push packet to "
            "decoder', rerun with --num_workers=0 or --dataset.video_backend=pyav "
            "(HANDOFF §1.6).",
            _VIDEO_QUERY_ATTRS,
        )
    else:
        logger.info(
            "No video-query method found to no-op (tried %s), but the DataLoader "
            "is not forking (spawn/forkserver) — the torchcodec fork crash "
            "(HANDOFF §1.6) does not apply here, so this is harmless.",
            _VIDEO_QUERY_ATTRS,
        )
    return None, None


def recompute_relative_stats(wrapped: RelativePoseDataset, num_samples: int = 2000) -> None:
    """Patch dataset.meta.stats for pose keys with stats of the RELATIVE values.

    LeRobot's NormalizerProcessor uses dataset-wide stats computed on the raw
    (absolute) Parquet values. After the relative conversion the distributions
    are completely different, so we sample the wrapped dataset and overwrite
    the stats for the converted keys (and add stats for WRT_START_KEY).
    """
    keys = [k for k in POSE_OBS_KEYS] + [STATE_KEY, POSE_ACTION_KEY, WRT_START_KEY]
    n = len(wrapped)
    indices = np.linspace(0, n - 1, min(num_samples, n)).astype(int)

    # CRITICAL: do NOT decode video in this pass. It runs in the MAIN process,
    # and any torchcodec decoder opened here is forked into the DataLoader
    # workers in a broken state -> every worker dies at step 0 with
    # "Could not push packet to decoder: Invalid data found". (Plain
    # lerobot-train has no main-process stats pass, which is why it never hits
    # this.) The stats keys are all low-dim poses, so we no-op the dataset's
    # video query for the duration of sampling; lerobot's temporal windowing of
    # the low-dim columns is unaffected, so the action-horizon stats stay exact.
    ds = wrapped._dataset
    _attr, _orig = _disable_video_query(ds)
    try:
        collected: dict[str, list[np.ndarray]] = {k: [] for k in keys}
        for i in indices:
            item = wrapped[int(i)]
            for k in keys:
                if k in item:
                    v = item[k]
                    v = v.numpy() if isinstance(v, torch.Tensor) else np.asarray(v)
                    collected[k].append(v.reshape(-1, v.shape[-1]))
    finally:
        if _attr is not None:
            setattr(ds, _attr, _orig)

    for k, chunks in collected.items():
        if not chunks:
            continue
        data = np.concatenate(chunks, axis=0)
        wrapped.meta.stats[k] = {
            "mean": torch.from_numpy(data.mean(axis=0).astype(np.float32)),
            "std": torch.from_numpy((data.std(axis=0) + 1e-8).astype(np.float32)),
            "min": torch.from_numpy(data.min(axis=0).astype(np.float32)),
            "max": torch.from_numpy(data.max(axis=0).astype(np.float32)),
        }
        logger.info(f"Recomputed relative-pose stats for '{k}' over {len(data)} frames.")


# ── Provenance stamping ───────────────────────────────────────────────────────

def _installed_lerobot_version() -> str:
    """Version of the lerobot actually importable in this interpreter.

    Returns "unknown" rather than raising: this is provenance metadata and must
    never be the reason a training run dies.
    """
    try:
        from importlib.metadata import version

        return version("lerobot")
    except Exception:  # not installed via metadata (editable/source checkout)
        try:
            import lerobot

            return getattr(lerobot, "__version__", "unknown")
        except Exception:
            return "unknown"


def stamp_pose_repr(cfg, dataset) -> None:
    """Write pose_repr.json next to the checkpoints (HANDOFF §4.2).

    Records what the model ACTUALLY sees, so the serving side (remote policy
    server / local RelativeLerobotPolicy) can verify its contract instead of
    guessing. Never fails training.
    """
    import json
    from pathlib import Path

    try:
        pol = getattr(cfg, "policy", None)
        meta = getattr(dataset, "meta", None)

        # Machine-readable composition of the observation.state tensor the
        # MODEL consumes: ordered sub-key components (from the dataset's real
        # feature layout) + the wrapper-generated wrt-start block. This is
        # what lets a policy server / deploy client BUILD the state instead
        # of guessing from prose. transform enum:
        #   none | relative_to_last_obs_frame | wrt_episode_start_rotation
        state_components = None
        features = getattr(meta, "features", None) or {}
        if STATE_KEY in features:
            append_wrt = bool(getattr(dataset, "_append_wrt", True))
            comps = []
            for key in features:
                if not key.startswith(STATE_KEY + ".") or key == WRT_START_KEY:
                    continue
                comps.append({
                    "key": key,
                    "dims": int(np.prod(features[key]["shape"])),
                    "transform": (
                        "relative_to_last_obs_frame" if key == BASE_KEY else "none"
                    ),
                })
            if append_wrt:
                comps.append({
                    "generated": "rot_wrt_start",
                    "dims": 6,
                    "transform": "wrt_episode_start_rotation",
                    "rotation_only": True,
                    "noise_train_only": START_POSE_NOISE_SCALE,
                })
            total = sum(c["dims"] for c in comps)
            state_dim = int(np.prod(features[STATE_KEY]["shape"]))
            if total == state_dim:
                state_components = comps
            else:
                logger.warning(
                    f"state_components dims sum {total} != {STATE_KEY} dim "
                    f"{state_dim} — omitting components from pose_repr.json "
                    "(sub-features do not fully describe the concat)."
                )

        info = {
            "pose_layout": "pos3_rot6d_rows",
            "rot6d_convention": "first_two_rows_row_major_gram_schmidt_decode",
            "action": {
                "pose_repr": "relative",
                "base": "last_obs_frame_tcp",
                "compose_base": "obs_time",
                "layout": "[x, y, z, rot6d(6), gripper]",
            },
            "observation": {
                # lerobot-0.4.4 policies consume the CONCATENATED
                # observation.state; its pose dims are converted, so the
                # MODEL INPUT is relative (current frame -> identity), and the
                # wrt-start rot6d is APPENDED (UMI 16-D parity). Checkpoints
                # trained BEFORE these conversions have no pose_repr.json (or
                # one without these fields) — the deploy side keys its
                # behavior off them.
                "observation.state": "relative_to_last_obs_frame",
                "observation.state.cartesian": "relative_to_last_obs_frame",
                # Deploy side: generate wrt-start (rotation-only, NOISE OFF)
                # from the episode-start pose and append after all other dims.
                "state_includes_wrt_start": True,
                "state_layout": "[rel_pose9, gripper1(, extras...), rot_wrt_start6]",
                # Ordered, machine-readable composition of observation.state
                # (None when the sub-features can't fully describe the concat).
                "state_components": state_components,
                "wrt_start_key": WRT_START_KEY,
                "start_pose_noise_scale": START_POSE_NOISE_SCALE,
            },
            "gripper": {
                "semantics": "clip(width_m / reference_width, 0, 1)",
                "note": "reference_width/device_max_width are stamped in the "
                        "dataset's meta/record_config.json",
            },
            "normalization": "relative stats recomputed pre-training "
                             "(recompute_relative_stats), saved with checkpoint",
            "fps": getattr(meta, "fps", None),
            "n_obs_steps": getattr(pol, "n_obs_steps", None),
            "horizon": getattr(pol, "horizon", None),
            "n_action_steps": getattr(pol, "n_action_steps", None),
            # The lerobot that actually produced this checkpoint, detected at
            # run time. Was hardcoded "0.4.4" when that was the only supported
            # version; the wrapper now runs on 0.4.x and >=0.5 alike, so a
            # fixed string would misreport provenance. Nothing consumes this
            # field (the deploy path reads observation.* only) — it is for
            # humans reading pose_repr.json next to a checkpoint.
            "lerobot_version_target": _installed_lerobot_version(),
        }
        out_dir = Path(cfg.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "pose_repr.json").write_text(json.dumps(info, indent=2))
        logger.info(f"Stamped {out_dir / 'pose_repr.json'}")
    except Exception as e:  # provenance must never kill a training run
        logger.warning(f"Could not stamp pose_repr.json: {e}")


# ── Training launcher ─────────────────────────────────────────────────────────

def main():
    """Run lerobot-train with the relative-pose dataset wrapper injected.

    The dataset factory is monkeypatched in lerobot_train's module namespace;
    train() resolves it as a global at call time, so rebinding the attribute is
    enough. The symbol differs by lerobot version:

      0.6.x: make_train_eval_datasets(cfg) -> (dataset, eval_dataset)
      0.4.x: make_dataset(cfg)             -> dataset

    Both are supported so the script runs against either. Neither present means
    lerobot moved the factory again — fail with a pointer rather than training
    on ABSOLUTE poses, which would look normal and be silently wrong.

    CLI: --no-wrt-start trains a plain 10-D relative-state model; the default
    (--wrt-start) appends rot_wrt_start for the 16-D UMI-parity state. Deploy
    must match (RelativeLerobotPolicy state_input relative vs relative_wrt_start).
    These are OUR flags — stripped from argv before draccus parses the rest.
    """
    import sys

    import lerobot.scripts.lerobot_train as lerobot_train

    append_wrt, remaining = _pop_wrt_start_flag(sys.argv[1:])
    sys.argv = [sys.argv[0]] + remaining
    logging.basicConfig(level=logging.INFO)
    logger.info(
        "append_wrt_start_to_state=%s -> %s observation.state.",
        append_wrt, "16-D UMI-parity" if append_wrt else "10-D relative",
    )

    def _wrap(dataset, cfg):
        wrapped = RelativePoseDataset(dataset, append_wrt_start_to_state=append_wrt)
        logger.info("Wrapped dataset with RelativePoseDataset (UMI-style relative poses).")
        recompute_relative_stats(wrapped)
        stamp_pose_repr(cfg, wrapped)
        return wrapped

    if hasattr(lerobot_train, "make_train_eval_datasets"):  # lerobot >= 0.5
        original_pair = lerobot_train.make_train_eval_datasets

        def make_train_eval_with_relative(cfg):
            dataset, eval_dataset = original_pair(cfg)
            wrapped = _wrap(dataset, cfg)
            if eval_dataset is not None:
                # Wrap the eval split too: leaving it absolute would evaluate a
                # relative-trained policy against absolute targets, which
                # produces plausible-looking but meaningless metrics — no error.
                # Stats/stamp stay train-only, as they always were.
                eval_dataset = RelativePoseDataset(
                    eval_dataset, append_wrt_start_to_state=append_wrt
                )
                logger.info("Wrapped eval dataset with RelativePoseDataset.")
            return wrapped, eval_dataset

        lerobot_train.make_train_eval_datasets = make_train_eval_with_relative
        logger.info("Patched lerobot_train.make_train_eval_datasets (lerobot >= 0.5 layout).")
    elif hasattr(lerobot_train, "make_dataset"):  # lerobot 0.4.x
        original_single = lerobot_train.make_dataset

        def make_dataset_with_relative(cfg):
            return _wrap(original_single(cfg), cfg)

        lerobot_train.make_dataset = make_dataset_with_relative
        logger.info("Patched lerobot_train.make_dataset (lerobot 0.4.x layout).")
    else:
        raise RuntimeError(
            "lerobot.scripts.lerobot_train exposes neither 'make_train_eval_datasets' "
            "(>=0.5) nor 'make_dataset' (0.4.x) — the relative-pose wrapper cannot be "
            "injected. Without it training would silently run on ABSOLUTE poses. "
            "Find the dataset factory lerobot_train now calls and patch that name."
        )

    lerobot_train.main()


def _pop_wrt_start_flag(argv: list[str]) -> tuple[bool, list[str]]:
    """Consume --wrt-start / --no-wrt-start from argv (default: True).

    These are OUR flags, not lerobot's, so strip them before draccus parses the
    rest or it raises 'unrecognized arguments'.

    Returns:
        (append_wrt_start, remaining_argv)
    """
    append_wrt = True
    remaining = []
    for a in argv:
        if a == "--wrt-start":
            append_wrt = True
        elif a == "--no-wrt-start":
            append_wrt = False
        else:
            remaining.append(a)
    return append_wrt, remaining


if __name__ == "__main__":
    main()
