filter.q: 0.5
filter.dq: 0.5
filter.output_torque: 0.5

task.k_pos_x: 400.0
task.k_pos_y: 400.0
task.k_pos_z: 400.0
task.k_rot_x: 30.0
task.k_rot_y: 30.0
task.k_rot_z: 30.0

nullspace.stiffness: 2.0

use_friction: false
use_coriolis_compensation: true
use_local_jacobian: true
use_gravity_compensation: false
