filter.q: 0.5
filter.dq: 0.5
filter.output_torque: 0.5

task.k_pos_x: 200.0
task.k_pos_y: 200.0
task.k_pos_z: 200.0
task.k_rot_x: 60.0
task.k_rot_y: 60.0
task.k_rot_z: 60.0

nullspace.stiffness: 0.0

use_friction: false
use_coriolis_compensation: true
use_local_jacobian: true
use_gravity_compensation: false
use_operational_space: true
